/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiooptest;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rohovszky.akos
 */
public class GuiOOPTest extends javax.swing.JFrame {

    JButton[] pinButtons;
    
    /**
     * Creates new form GuiOOPTest
     */
    public GuiOOPTest() {
        initComponents();
        createPinButtions();
        showPinButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elrendezés = new javax.swing.ButtonGroup();
        startingSymbol = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        bejelentkezésPanel = new javax.swing.JPanel();
        pinPadPanel = new javax.swing.JPanel();
        loginSettingsPanel = new javax.swing.JPanel();
        shuffleCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        pinCodeTextField = new javax.swing.JTextField();
        jatekPanel = new javax.swing.JPanel();
        tictactoePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        XStartButton = new javax.swing.JRadioButton();
        OStartButton = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(410, 350));
        setMinimumSize(new java.awt.Dimension(410, 350));
        setPreferredSize(new java.awt.Dimension(410, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(410, 250));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(410, 350));

        bejelentkezésPanel.setName(""); // NOI18N

        pinPadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pin kód"));
        pinPadPanel.setLayout(new java.awt.GridLayout(4, 3));

        loginSettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Beállítás"));

        shuffleCheckBox.setText("kever");
        shuffleCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shuffleCheckBoxStateChanged(evt);
            }
        });
        shuffleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shuffleCheckBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("kód:");

        javax.swing.GroupLayout loginSettingsPanelLayout = new javax.swing.GroupLayout(loginSettingsPanel);
        loginSettingsPanel.setLayout(loginSettingsPanelLayout);
        loginSettingsPanelLayout.setHorizontalGroup(
            loginSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pinCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addGroup(loginSettingsPanelLayout.createSequentialGroup()
                        .addGroup(loginSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shuffleCheckBox)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginSettingsPanelLayout.setVerticalGroup(
            loginSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginSettingsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(shuffleCheckBox)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bejelentkezésPanelLayout = new javax.swing.GroupLayout(bejelentkezésPanel);
        bejelentkezésPanel.setLayout(bejelentkezésPanelLayout);
        bejelentkezésPanelLayout.setHorizontalGroup(
            bejelentkezésPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bejelentkezésPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pinPadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bejelentkezésPanelLayout.setVerticalGroup(
            bejelentkezésPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bejelentkezésPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bejelentkezésPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pinPadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bejelentkezés", bejelentkezésPanel);

        tictactoePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Amőba"));

        javax.swing.GroupLayout tictactoePanelLayout = new javax.swing.GroupLayout(tictactoePanel);
        tictactoePanel.setLayout(tictactoePanelLayout);
        tictactoePanelLayout.setHorizontalGroup(
            tictactoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        tictactoePanelLayout.setVerticalGroup(
            tictactoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Beállítás"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(30, 70));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "3*3", "4*4", "5*5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel2.add(jScrollPane2);

        startingSymbol.add(XStartButton);
        XStartButton.setSelected(true);
        XStartButton.setText("\"X\" kezd");
        jPanel2.add(XStartButton);

        startingSymbol.add(OStartButton);
        OStartButton.setText("\"O\" kezd");
        jPanel2.add(OStartButton);

        javax.swing.GroupLayout jatekPanelLayout = new javax.swing.GroupLayout(jatekPanel);
        jatekPanel.setLayout(jatekPanelLayout);
        jatekPanelLayout.setHorizontalGroup(
            jatekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatekPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tictactoePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jatekPanelLayout.setVerticalGroup(
            jatekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatekPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jatekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tictactoePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Játék", jatekPanel);

        jMenu2.setText("Program");

        jMenuItem1.setText("Újra");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Kilépés");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Játék elrendezése");
        elrendezés.add(jMenu3);

        elrendezés.add(jCheckBoxMenuItem1);
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("vizszintes");
        jMenu3.add(jCheckBoxMenuItem1);

        elrendezés.add(jCheckBoxMenuItem2);
        jCheckBoxMenuItem2.setText("függőleges");
        jMenu3.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shuffleCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_shuffleCheckBoxStateChanged
        
    }//GEN-LAST:event_shuffleCheckBoxStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closingWindow();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        closingWindow();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        restart();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void shuffleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shuffleCheckBoxActionPerformed
        clickShuffleButton();
    }//GEN-LAST:event_shuffleCheckBoxActionPerformed

    private void closingWindow() {
        int res = JOptionPane.showConfirmDialog(this, "Kilépsz?","Kilépés", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(res == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }
    
    private void clickPinButton(ActionEvent e) {
        JButton but = (JButton)e.getSource();
        but.setBackground(Color.CYAN);
        String num = but.getText();
        pinCodeTextField.setText(pinCodeTextField.getText() + num);
    }
    
    private void showPinButtons() {
        pinPadPanel.removeAll();
        for (JButton button : this.pinButtons) {
            pinPadPanel.add(button);
        }
        pinPadPanel.revalidate();
    }
    
    private void clickShuffleButton() {
        if(shuffleCheckBox.isSelected()) {
            shufflePinButtons();
            showPinButtons();
        }
        else {
            createPinButtions();
            showPinButtons();
        }
    }
    
    private void shufflePinButtons() {
        JButton[] newButtons = new JButton[10];
        int placed = 0;
//        while (placed < 10) {
        for(int l = 0; l < 100; l++) {
            int num = (int)(Math.random() * 10);
            if(newButtons[num] == null) {
                newButtons[num] = this.pinButtons[placed];
                placed++;
            }
        }
        this.pinButtons = newButtons;
    }
    
    private void createPinButtions() {
        this.pinButtons = new JButton[10];
        for (int x = 0; x < 10; x++) {
            JButton but = new JButton(Integer.toString((x+1)%10));
            but.addActionListener(this::clickPinButton);
            this.pinButtons[x] = but;
        }
    }
    
    private void restart() {
        pinCodeTextField.setText("");
        shuffleCheckBox.setSelected(false);
        createPinButtions();
        showPinButtons();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiOOPTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiOOPTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiOOPTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiOOPTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiOOPTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton OStartButton;
    private javax.swing.JRadioButton XStartButton;
    private javax.swing.JPanel bejelentkezésPanel;
    private javax.swing.ButtonGroup elrendezés;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jatekPanel;
    private javax.swing.JPanel loginSettingsPanel;
    private javax.swing.JTextField pinCodeTextField;
    private javax.swing.JPanel pinPadPanel;
    private javax.swing.JCheckBox shuffleCheckBox;
    private javax.swing.ButtonGroup startingSymbol;
    private javax.swing.JPanel tictactoePanel;
    // End of variables declaration//GEN-END:variables

}
